# Generated by Django 5.1.7 on 2025-03-06 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('tournament', models.IntegerField(default=0)),
                ('tournament_played', models.IntegerField(default=0)),
                ('tournament_wins', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
                ('games_wins', models.IntegerField(default=0)),
                ('games_loses', models.IntegerField(default=0)),
                ('games_draws', models.IntegerField(default=0)),
                ('winrate', models.FloatField(default=0)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.level')),
            ],
        ),
    ]
