# Generated by Django 5.1.7 on 2025-03-06 19:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('status', models.IntegerField(default=0)),
                ('players', models.IntegerField(default=0)),
                ('max_players', models.IntegerField(default=0)),
                ('rounds', models.IntegerField(default=0)),
                ('round', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Creator', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='videogame', to='main.videogame')),
                ('min_level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='level', to='main.level')),
                ('tournament_winner', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tournament_winner', to='users.players')),
            ],
        ),
        migrations.CreateModel(
            name='PlayersTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.IntegerField(default=0)),
                ('draw', models.IntegerField(default=0)),
                ('lose', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('player', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_tournament', to='users.players')),
                ('tournament', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tournament_player', to='tournaments.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='GameAux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(default=0)),
                ('result_player1', models.IntegerField(default=0)),
                ('result_player2', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='player1_aux', to='users.players')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='player2_aux', to='users.players')),
                ('player_sender', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_sender', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_winner_aux', to='users.players')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tournament_aux', to='tournaments.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(default=0)),
                ('result_player1', models.IntegerField(default=0)),
                ('result_player2', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(default=0)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='player1', to='users.players')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='player2', to='users.players')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_winner', to='users.players')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tournament', to='tournaments.tournament')),
            ],
        ),
    ]
